<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<MapBrokers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="MapBrokers_2.xsd">
   <MapBroker dmlCompatibility="2.1" id="ddec0D26-706a-4db5-a7ac-a14fde47f3f3" label="" lastModified="2024-07-29T15:12:14.000Z" name="MAPSERVICE_Sinacofi_D26_F1_D26_FRONT::MAPSERVICE.Sinacofi_D26_F1.Evento_Error" xmlVersion="1.0">
      <DmlMapBroker>
         <InputBusinessDocuments/>
         <DecisionPath>
            <StepIf>
               <DmlExpression><![CDATA[countString(getTraces(), "IO Error: The Network Adapter could not establish the connection") = 0]]></DmlExpression>
               <StepStep>
                  <DmlExpression><![CDATA[%debug:= getTraces();
if( (%var_error1 <> "OK"))then{
		%var_error1:=Sinacofi_D26_F1.InsertErrorTBL(
			%correlativoPrefijo,
			"000", 
			"Error Interno: "&getSubString(%debug, 1, 4000), 
			formatString(getDateAndTime(), "CCYY'-'MM'-'DD hh':'mm':'ss")
		)
};
%var_error1:= InsertMovTBL(%correlativoPrefijo, null, %var_registro1, null, "00", formatString(getDateAndTime(), "CCYY'-'MM'-'DD hh':'mm':'ss"))
]]></DmlExpression>
               </StepStep>
            </StepIf>
            <StepExit/>
         </DecisionPath>
      </DmlMapBroker>
   </MapBroker>
</MapBrokers>
